services:
  db:
    image: postgres:15-alpine
    container_name: booking-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./sql_script:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  #  redis:
  #    image: redis:7-alpine
  #    container_name: booking-cache
  #    ports:
  #      - "6379:6379"
  #    restart: always

volumes:
  postgres_data:
